version: '3.3'
services:
  couchbase:
    image: couchbase:community-6.0.0
  queue:
    image: rabbitmq:3
    # Using the below image instead is required to enable the "Broker" tab in the flower UI:
    # image: rabbitmq:3-management
    #
    # You also have to change the flower command as documented in docker-compose.shared.admin.yml
